definitions:
  AddCategoryRequest:
    properties:
      date:
        example: "2020-06-29T00:00:00Z"
        type: string
      name:
        example: закуски
        type: string
    required:
    - name
    type: object
  AddClothesRequest:
    properties:
      color:
        type: string
      count:
        type: integer
      name:
        type: string
      price:
        type: number
      stock:
        type: string
      type:
        type: string
    type: object
  DeleteClothesRequest:
    properties:
      count:
        type: integer
    type: object
  ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  LoginRequest:
    properties:
      email:
        example: admin@mail.ru
        type: string
      password:
        example: Password12!
        type: string
    required:
    - email
    - password
    type: object
  UpdateCategoryRequest:
    properties:
      name:
        example: веган
        type: string
    required:
    - name
    type: object
  domain.Category:
    properties:
      date:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  domain.Clothes:
    properties:
      color:
        type: string
      count:
        type: integer
      id:
        type: string
      name:
        type: string
      price:
        type: integer
      stock:
        type: string
      type:
        type: string
    type: object
  request.User:
    properties:
      email:
        example: razor3538@mail.ru
        type: string
      firstName:
        example: Edos
        type: string
      lastName:
        example: Gaifut
        type: string
    type: object
  request.UserUpdate:
    properties:
      email:
        example: razzzor3538@mail.ru
        type: string
      firstName:
        example: Eduard
        type: string
      lastName:
        example: Gaifutdinov
        type: string
    type: object
  response.User:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      role:
        type: string
      status:
        type: string
    type: object
  response.UserResponse:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      role:
        type: string
      status:
        type: string
    type: object
  usecase.Category:
    type: object
info:
  contact: {}
  license: {}
  title: ZooArk
  version: 1.0.0
paths:
  /categories:
    get:
      parameters:
      - description: in format YYYY-MM-DDT00:00:00Z
        in: query
        name: date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: array of category readings
          schema:
            items:
              $ref: '#/definitions/domain.Category'
            type: array
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get list of categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      parameters:
      - description: Category Name
        in: body
        name: body
        schema:
          $ref: '#/definitions/AddCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: category object
          schema:
            $ref: '#/definitions/usecase.Category'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns error if exists and 200 if success
      tags:
      - categories
  /categories/{id}:
    delete:
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Successfully deleted
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Soft delete
      tags:
      - categories
    put:
      consumes:
      - application/json
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: new category name
        in: body
        name: body
        schema:
          $ref: '#/definitions/UpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "204":
          description: Successfully updated
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns 204 if success and 4xx error if failed
      tags:
      - categories
  /is-authenticated:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns user info if authorized
      tags:
      - auth
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Credentials
        in: body
        name: body
        schema:
          $ref: '#/definitions/LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "401":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns info about user
      tags:
      - auth
  /logout:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/ErrorResponse'
        "401":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Removes cookie if set
      tags:
      - auth
  /products/clothes:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: List of clothes
          schema:
            items:
              $ref: '#/definitions/domain.Clothes'
            type: array
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns list of clothes
      tags:
      - clothes
    post:
      parameters:
      - description: clothes object
        in: body
        name: payload
        schema:
          $ref: '#/definitions/AddClothesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: clothes object
          schema:
            $ref: '#/definitions/domain.Clothes'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - clothes
  /products/clothes/{id}:
    delete:
      parameters:
      - description: Clothes ID
        in: path
        name: id
        required: true
        type: string
      - description: clothes object
        in: body
        name: payload
        schema:
          $ref: '#/definitions/DeleteClothesRequest'
      produces:
      - application/json
      responses:
        "204":
          description: Successfully deleted
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Soft delete
      tags:
      - clothes
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.User'
      produces:
      - application/json
      responses:
        "201":
          description: User
          schema:
            $ref: '#/definitions/response.User'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns error or 201 status code if success
      tags:
      - Users
  /users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Successfully deleted
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns error or 204 status code if success
      tags:
      - Users
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        type: string
      - description: User
        in: body
        name: body
        schema:
          $ref: '#/definitions/request.UserUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Catering user
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns error or 200 status code if success
      tags:
      - Users
swagger: "2.0"
