definitions:
  AddProductRequest:
    properties:
      count:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
  ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  LoginRequest:
    properties:
      email:
        example: admin@mail.ru
        type: string
      password:
        example: Password12!
        type: string
    required:
    - email
    - password
    type: object
  domain.Product:
    properties:
      count:
        type: integer
      id:
        type: string
      name:
        type: string
      price:
        type: integer
    type: object
  response.UserResponse:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      role:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: ZooArk
  version: 1.0.0
paths:
  /is-authenticated:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns user info if authorized
      tags:
      - auth
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Credentials
        in: body
        name: body
        schema:
          $ref: '#/definitions/LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "401":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Returns info about user
      tags:
      - auth
  /logout:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/ErrorResponse'
        "401":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Removes cookie if set
      tags:
      - auth
  /products:
    post:
      parameters:
      - description: product object
        in: body
        name: payload
        schema:
          $ref: '#/definitions/AddProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: product object
          schema:
            $ref: '#/definitions/domain.Product'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
      - product
swagger: "2.0"
